# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: clevr_count-full-lr-0.15
  max_steps: 10000
  val_check_interval: 500
model:
  model_name: vit-b16-224-dino
  training_mode: full
  optimizer: sgd
  lr: 0.15
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
data:
  dataset: custom
  root: clevr_count
  size: 224
  batch_size: 64
  workers: 4
  num_classes: 8
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max
